public enum RObjectType {
	BLANK = 0,
	STANDARD = 1,
	POINT = 2,
	FALLING = 3,
	SLIP = 4,
	ITEM = 5,
	ARROW = 6,
	WIND_UP = 7,
	WIND_DOWN = 8,
	WIND_0 = 9,
	STOP = 10,
	MOVE_UP = 11,
	MOVE_RIGHT = 12,
	MOVE_DOWN = 13,
	MOVE_LEFT = 14,
	WIND_NONE_GRAVITY = 15
}